/** CSS variables emitted by the theme contract. Feature code uses these, never raw palette values. */
export const semantic = {
  canvas: "var(--color-canvas)",
  surface: "var(--color-surface)",
  surfaceElevated: "var(--color-surface-elevated)",
  textPrimary: "var(--color-text-primary)",
  textSecondary: "var(--color-text-secondary)",
  textMuted: "var(--color-text-muted)",
  border: "var(--color-border)",
  borderStrong: "var(--color-border-strong)",
  accent: "var(--color-accent)",
  accentHover: "var(--color-accent-hover)",
  accentActive: "var(--color-accent-active)",
  accentContrast: "var(--color-accent-contrast)",
  focusRing: "var(--color-focus-ring)",
  positive: "var(--color-positive)",
  caution: "var(--color-caution)",
  negative: "var(--color-negative)",
  fontBody: "var(--font-body)",
  fontDisplay: "var(--font-display)",
  radiusSm: "var(--radius-sm)",
  radiusMd: "var(--radius-md)",
  radiusLg: "var(--radius-lg)",
} as const;
